// data.js
const flashcardsCategories = {
    "Organi": [
        {
            q: "Il Sindaco",
            a: "Il Sindaco è l’organo di vertice del Comune. È il rappresentante legale dell’ente e ne assume la responsabilità politica e amministrativa. \nPresiede la Giunta, si occupa delle nomine, coordina l’attività degli assessori e vigila sul buon andamento dei servizi e degli uffici (esecuzione atti). \nEsercita inoltre funzioni come ufficiale di governo (funzione statale), ad esempio in materia di stato civile (nascite, matrimoni, morte), anagrafe (carta d’identità, residenza) pubblica sicurezza (degrado, pericoli) e statistica (censimento popolazione annuale) \n\nÈ eletto direttamente dai cittadini e resta in carica per cinque anni, con un limite di 2 mandati consecutivi, salvo deroghe per piccoli comuni."
        },
        {
            q: "Il Sindaco: Carica e Provvedimenti",
            a: "La carica può cessare per cause naturali, dimissioni (irrevocabili dopo 20 giorni) o per mozione di sfiducia. Quest'ultima richiede la firma di 2/5 dei consiglieri e il voto favorevole della maggioranza assoluta; la sua approvazione comporta, per il principio simul stabunt simul cadent, la caduta della Giunta, del Consiglio e l'invio di un Commissario Prefettizio. \n\nPer quanto riguarda i provvedimenti, può emanare Decreti sindacali, ovvero atti fiduciari con i quali assegnare nomine e deleghe e può emanare Ordinanze, ovvero atti che servono per gestire emergenze o dettare regole ai cittadini. Queste possono essere Ordinanze Ordinarie, per imporre divieti o regole basate su regolamenti esistenti (es. divieto di sosta per pulizia strade) o Ordinanze Contingibili e Urgenti, che permettono al Sindaco di fare un'eccezione alla legge per affrontare situazioni eccezionali, imprevedibili e urgenti. (es. un crollo stradale, un epidemia locale)."
        },
        {
            q: "Il Consiglio Comunale",
            a: "Il Consiglio Comunale è l’organo collegiale di indirizzo e controllo politico-amministrativo. È composto da membri eletti dai cittadini (minimo di 6, massimo 48, in proporzione agli abitanti) ed è presieduto da un Presidente. Ha compiti fondamentali, come approvare lo statuto, i regolamenti e il bilancio. Controlla il lavoro del Sindaco e della Giunta e garantisce trasparenza e rappresentanza democratica. Le sue decisioni si esprimono attraverso deliberazioni. \n\nLa figura del Presidente del Consiglio è posta a garanzia dell'organo, ne cura la convocazione e conduce le sedute; è obbligatoria sopra i 15.000 abitanti, mentre sotto tale soglia le sue funzioni possono essere esercitate dal Sindaco. \n\nIl Consiglio può essere sciolto per crisi politica (sfiducia, dimissioni), inerzia (mancato bilancio) o infiltrazioni mafiose. La competenza finale è del Presidente della Repubblica, su proposta del Ministro dell'Interno, dopo segnalazione del Prefetto. L'effetto immediato è la nomina di un Commissario che sostituisce tutti gli organi elettivi fino a nuove elezioni. \n\nPer quanto riguarda il potere programmatico, il Consiglio lo esercita approvando i principali strumenti di pianificazione dell'ente, come il DUP (Documento Unico di Programmazione), il Bilancio di Previsione e il Piano Triennale delle Opere Pubbliche. In questo modo definisce gli obiettivi e le priorità dell'azione amministrativa, che poi la Giunta e i dirigenti si occupano di attuare."
        },
        {
            q: "La Giunta Comunale",
            a: "La Giunta Comunale è l’organo esecutivo del Comune. È guidata dal Sindaco e composta da un numero variabile di assessori scelti da lui. Ha competenze residuali, ovvero si occupa di tutto ciò che non è espressamente previsto per il Sindaco o il Consiglio Comunale. Mentre il consiglio comunale definisce le linee politiche e amministrative generali, la giunta si occupa di metterle in pratica, prendendo decisioni operative sul bilancio, regolamenti e gestione dei servizi, lavorando a stretto contatto con il Sindaco. \n\nA livello pratico, predispone lo schema del Bilancio di Previsione e del Rendiconto da sottoporre al Consiglio, e redige il PEG. Può variare il bilancio in casi d'urgenza (che poi il Consiglio deve approvare entro 60 giorni). Inoltre approva il Regolamento degli Uffici e dei Servizi (ROUS) e il fabbisogno del personale. \n\nSul piano del funzionamento interno, la Giunta decide a maggioranza (assoluta, ma dei presenti) e le sue sedute sono segrete. Ad ogni seduta, il Segretario Comunale redige il verbale, che tiene traccia di quanto discusso e deliberato. Infine, ogni delibera che comporta una spesa deve essere accompagnata da un parere tecnico — che attesta la fattibilità dell'atto — e da un parere contabile — che verifica la copertura finanziaria."
        },
        {
            q: "Il Segretario Generale",
            a: "Il Segretario Generale è una figura centrale nel Comune. Viene nominato dal Sindaco e ha il compito di garantire che gli atti dell’amministrazione siano regolari dal punto di vista giuridico. Partecipa alle sedute di Giunta e Consiglio, redige i verbali e può anche firmare i contratti ufficiali (es acquisto di un terreno). Coordina l’attività amministrativa e supporta gli organi politici per assicurare correttezza e trasparenza nell’azione amministrativa. \n\nÈ inoltre responsabile dell’anticorruzione, vigilando sui conflitti di interesse, e predisponendo ogni anno il Piano Triennale per la Prevenzione della Corruzione e della Trasparenza. \n\nÈ come un \"supervisore\" che fa in modo che l'amministrazione funzioni bene e senza problemi.come se fosse il capo dei capi dei dirigenti, quando non c’è direttore generale \n\nAd esempio se nasce una discussione accesa durante una seduta, verbalizza tutto in modo imparziale."
        },
        {
            q: "Il Direttore Generale",
            a: "Il Direttore Generale è una figura che può essere nominata dal Sindaco nei Comuni con più di 100.000 abitanti, come Milano. (È tipo l’amministratore delegato) Il suo compito principale è quello di coordinare tutta l’attività gestionale dell’ente, assicurando che gli obiettivi dell’amministrazione vengano raggiunti in modo efficiente. Lavora a stretto contatto con i dirigenti e con il Segretario Generale, e si occupa di ottimizzare l’organizzazione degli uffici e dei progetti. Quando non c’è, ad esempio nei comuni piccoli, i suoi compiti sono svolti dal Segretario. \n\n Ad esempio segue un progetto voluto dal sindaco (tipo nuovo tram), convocando i dirigenti dei vari settori, coordinandoli, eventualmente gestendo il personale. Descrive gli obbiettivi concreti da inserire nel PEG e monitora periodicamente l’avanzamento dei lavori."
        },
        {
            q: "I Dirigenti",
            a: "I dirigenti sono le figure responsabili di organizzare e gestire le strutture amministrative loro affidate e di realizzare gli obiettivi fissati dagli organi politici. Hanno autonomia gestionale, tecnica e contabile, e devono garantire l’efficienza, l’efficacia e la trasparenza dell’attività amministrativa. \n\nSul piano normativo, la figura del dirigente è disciplinata principalmente da due testi fondamentali: il D.Lgs. 267/2000 (TUEL), che regola l'ordinamento degli enti locali, e il D.Lgs. 165/2001, che disciplina il rapporto di lavoro nelle pubbliche amministrazioni e sancisce il principio fondamentale della separazione tra indirizzo politico e gestione amministrativa: gli organi politici definiscono gli obiettivi, i dirigenti li realizzano in autonomia. \n\nPoi ti puoi collegare a segretario generale, giunta e PEG"
        }
    ],
    "Procedimenti": [
        {
            q: "Il procedimento amministrativo",
            a: "Il procedimento amministrativo è il percorso con cui la pubblica amministrazione adotta un provvedimento. Si articola in quattro fasi: l’iniziativa, che avvia il procedimento, su istanza di parte quando è il cittadino che si rivolge alla PA per ottenere qualcosa (es. un permesso di costruire, un'autorizzazione, un contributo) o d’ufficio, quando è la PA stessa che avvia il procedimento di propria iniziativa (es. avviare un procedimento disciplinare, emettere un'ordinanza, avviare un controllo).; l’istruttoria, dove si raccolgono informazioni e si sentono i soggetti interessati; la fase decisoria, in cui si adotta l’atto finale, che può essere un provvedimento scritto e motivato, un silenzio assenso o un accordo tra le parti; e infine la fase integrativa dell’efficacia, come la comunicazione o la pubblicazione. Ogni fase garantisce trasparenza, partecipazione e legalità. \n\nIl diritto di intervento (Artt. 7-10 L. 241/90) garantisce la partecipazione al procedimento a chiunque (pubblico, privato o associazioni) possa subire un pregiudizio dal provvedimento. Consiste nel diritto di accesso agli atti e di presentare memorie e documenti che la PA è obbligata a valutare"
        },
        {
            q: "La comunicazione di avvio del procedimento",
            a: "La comunicazione di avvio del procedimento è un atto fondamentale per garantire trasparenza e partecipazione. Deve contenere alcuni elementi essenziali: l’amministrazione che procede, l’oggetto, il responsabile del procedimento, l’ufficio a cui rivolgersi, i termini per concludere l’iter e le conseguenze in caso di inerzia. Va anche indicato il diritto di accesso agli atti. Tutto questo serve a mettere il cittadino nelle condizioni di far valere i propri diritti."
        },
        {
    q: "Il provvedimento amministrativo",
    a: "Il provvedimento amministrativo è l’atto finale del procedimento con cui la pubblica amministrazione prende una decisione che incide su interessi pubblici o privati. Deve essere motivato, legittimo e adottato dall’autorità competente. Tra gli elementi essenziali ci sono: l’intestazione (chi lo adotta), l’oggetto, la motivazione, la finalità e il destinatario. Può essere favorevole (ampliativi) o sfavorevole (ablatori) e deve sempre rispettare i principi di legalità, trasparenza e imparzialità."
},
{
    q: "Atto nullo (3 vizi)",
    a: "Un atto amministrativo è nullo quando presenta vizi così gravi da renderlo giuridicamente inesistente. I principali casi di nullità sono tre: quando manca degli elementi essenziali, come l’oggetto o la motivazione, quando presenta difetto assoluto di attribuzione, cioè l’atto è adottato da chi non ha alcun potere; oppure per violazione o elusione del giudicato. A differenza dell’annullabilità, la nullità può essere rilevata in qualsiasi momento."
},
{
    q: "Atto annullabile (3 vizi)",
    a: "Un atto amministrativo è annullabile quando presenta vizi meno gravi, ma comunque contrari alla legge. I principali sono: incompetenza relativa, cioè l’atto è adottato da un ufficio diverso da quello previsto; violazione di legge, come il mancato rispetto delle norme procedurali; e eccesso di potere, quando l’amministrazione agisce in modo illogico o arbitrario. In questi casi, l’atto è valido fino a quando non viene annullato, su ricorso o d’ufficio. \n\nL’annullamento ha effetti retroattivi e può sempre essere sanato."
},
{
    q: "Il responsabile del procedimento",
    a: "Il responsabile del procedimento è il funzionario incaricato di seguire tutte le fasi di un procedimento amministrativo. Viene individuato subito dopo l’avvio e ha il compito di curare l’istruttoria, raccogliere i pareri necessari a proporre o adottare il provvedimento finale. È anche il referente per i cittadini, quindi garantisce trasparenza, rispetto dei tempi e corretto svolgimento dell’iter. La sua figura è prevista dalla legge 241 del 1990. \n\nCosa fa se ritiene di dover rigettare? Quando il RdP si accorge che la richiesta non può essere accolta, non può semplicemente rifiutarla. Deve seguire la procedura dell'art. 10-bis della L. 241/1990. Prima invia al cittadino un preavviso di rigetto con i motivi ostativi. Da quel momento i termini si interrompono e il cittadino ha 10 giorni per presentare osservazioni. Se le osservazioni sono convincenti il RdP prosegue verso un esito positivo. Altrimenti emette il provvedimento di diniego, che deve contenere una motivazione rafforzata: deve ribadire i motivi del rigetto e spiegare perché le osservazioni del cittadino non sono state accolte — non può ignorarle. Se il RdP salta il preavviso e rigetta direttamente, il provvedimento è illegittimo e rischia di essere annullato dal TAR. \n\nCome favorisce partecipazione? Comunicazione, accesso agli atti, preavviso rigetto, diritto intervento"
},
{
    q: "Silenzio-assenso",
    a: "Il silenzio-assenso è una forma di semplificazione amministrativa prevista dalla legge. Significa che, se entro un certo termine l’amministrazione non risponde a una richiesta del cittadino, la risposta si considera positiva. In pratica, il silenzio equivale a un assenso. Vale però solo nei casi previsti dalla legge e non si applica se ci sono vincoli ambientali, paesaggistici o di sicurezza. È uno strumento pensato per velocizzare i tempi della burocrazia."
},
{
    q: "Accesso agli atti documentale",
    a: "L’accesso documentale è il diritto riconosciuto ai cittadini di prendere visione o ottenere copia dei documenti amministrativi che li riguardano. È regolato dalla legge 241 del 1990 e può essere esercitato da chi ha un interesse diretto, concreto e attuale. L’obiettivo è garantire trasparenza e tutela dei propri diritti. L’amministrazione può rifiutarlo solo in presenza di limiti precisi, come la riservatezza o la sicurezza pubblica, motivando il diniego. \n\nCosa si puo fare in caso di diniego? La prima è il ricorso al TAR, la via giurisdizionale. Va presentato entro 30 giorni dal rifiuto o dalla formazione del silenzio. È un rito abbreviato, ma richiede il contributo unificato (tassa) e solitamente un avvocato. Se accolto, il giudice ordina al Comune di esibire i documenti. La seconda è il ricorso al Difensore Civico, la via amministrativa, più semplice e gratuita, prevista dall'art. 25 della L. 241/90. Va presentato entro 30 giorni e il Difensore ha 30 giorni per esaminare la pratica. Se ritiene il rifiuto illegittimo, invita il Comune a riesaminare la decisione. A questo punto se il Comune non risponde o non conferma il diniego entro 15 giorni, l'accesso si intende automaticamente consentito — il silenzio gioca a favore del cittadino. > silenzio-assenso"
},
{
    q: "L’accesso civico e l’accesso generalizzato",
    a: "L’accesso civico permette a chiunque di chiedere documenti, dati o informazioni che le amministrazioni devono pubblicare per legge, quando non lo hanno fatto (tipo?). L’accesso generalizzato, invece, consente a chiunque di richiedere ulteriori documenti o dati, anche non obbligatoriamente pubblicati, per favorire trasparenza e controllo sull’operato pubblico. Entrambi non richiedono motivazione, ma le richieste devono avere finalità specifiche e delimitate, non consentendo un controllo indiscriminato o esplorativo Possono essere limitati per tutelare interessi come la privacy o la sicurezza. Se non si ottiene risposta si può fare segnalazione a ANAC. Controinteressati: I controinteressati sono quei soggetti che potrebbero subire un pregiudizio nel caso la richiesta degli interessati venisse accolta. Vengono individuati dalla PA in base alla casistica dell’accesso"
},
{
    q: "Sezione Amministrazione trasparente",
    a: "Il principio di trasparenza nella PA ha avuto un'evoluzione normativa progressiva. La L. 241/1990 ha posto le basi introducendo il diritto di accesso agli atti. La Legge Severino (L. 190/2012) ha dato una forte spinta alla trasparenza come strumento di prevenzione della corruzione, con l'immagine della PA come \"casa di vetro\". Il D.Lgs. 33/2013 (Decreto Trasparenza) ha reso operativo questo principio introducendo la sezione \"Amministrazione Trasparente\" sui siti istituzionali e l'accesso civico semplice: il diritto di ogni cittadino di pretendere la pubblicazione di documenti che la PA aveva l'obbligo di pubblicare ma ha omesso. La vera svolta è arrivata con il D.Lgs. 97/2016 (FOIA — Freedom of Information Act), che ha introdotto l'accesso civico generalizzato. \n\nCosa devono pubblicare gli enti sul sito: Gli enti sono obbligati a pubblicare in modo proattivo una serie di informazioni, tra cui: organizzazione e organigramma, compensi e curricula dei dirigenti e degli amministratori, bandi di concorso e di gara, bilanci e rendiconti, provvedimenti e delibere, performance e risultati raggiunti, e il PTPCT (Piano Triennale per la Prevenzione della Corruzione e della Trasparenza). L'Albo Pretorio è lo spazio ufficiale — oggi esclusivamente online sul sito istituzionale del Comune — dove vengono pubblicati determinati atti e provvedimenti, come Ordinanze del sindaco, delibere della giunta e del consiglio e bandi di concorso e di gara."
},
{
    q: "Conferenza di servizi",
    a: "La conferenza di servizi è uno strumento che aiuta a semplificare e velocizzare i procedimenti quando servono più pareri da diverse amministrazioni (siamo nella fase istruttoria). Permette di riunire tutti gli enti coinvolti, anche a distanza, per decidere insieme in tempi certi. Si distingue principalmente in 3 tipologie: preliminare, istruttoria e decisoria. Può essere obbligatoria o facoltativa e si usa spesso in ambiti come edilizia, ambiente e attività produttive. La decisione finale spetta all’amministrazione che guida il procedimento, tenendo conto delle opinioni prevalenti."
},
{
    q: "SCIA",
    a: "È uno strumento di semplificazione amministrativa. In pratica, se un cittadino o un impresa vuole avviare un'attività, ad esempio nel commercio o nell'edilizia, non deve più aspettare un permesso preventivo. È sufficiente avvisare semplicemente la Pubblica Amministrazione presentando una 'segnalazione' con tutti i documenti richiesti, e si può avviare subito l’attività senza attendere risposta. La PA, poi, ha 60 giorni per fare i suoi controlli e verificare che sia tutto in regola."
}
    ],
    "Digitale e GDPR": [
        {
    q: "Il domicilio digitale",
    a: "Il domicilio digitale è l’indirizzo elettronico, come una PEC, che una persona o un’impresa sceglie per ricevere comunicazioni ufficiali dalla Pubblica Amministrazione. È previsto dal Codice dell’Amministrazione Digitale e ha lo stesso valore legale della posta cartacea. Favorisce rapidità, tracciabilità e risparmio. Può essere registrato in appositi elenchi, come l’INI-PEC per professionisti e imprese, o l’ANPR per i cittadini."
},
{
    q: "Il documento informatico",
    a: "Il documento informatico è qualsiasi contenuto digitale che rappresenta atti, fatti o dati giuridicamente rilevanti. Ha pieno valore legale se rispetta i requisiti del Codice dell’Amministrazione Digitale, come l’integrità e l’autenticità. Può essere firmato digitalmente per garantire l’identità del sottoscrittore. È lo strumento base per la digitalizzazione della PA, in sostituzione del documento cartaceo. \n\nCosa vuol dire protocollare? Protocollare significa registrare ufficialmente un documento in entrata o in uscita dalla PA, assegnandogli un numero di protocollo (cioè un codice identificativo univoco) e annotando data, mittente/destinatario e oggetto. In pratica è come \"timbrare\" ufficialmente un documento per certificare che esiste, che è stato ricevuto o inviato, e in che data. Ti colleghi a documento informatico"
},
{
    q: "Trattamento dei dati personali",
    a: "Il trattamento dei dati personali comprende tutte le operazioni effettuate sui dati che identificano una persona fisica, come la raccolta, la conservazione, l'uso e la cancellazione. È regolato dal GDPR, che stabilisce principi fondamentali come la riservatezza, la correttezza, la trasparenza e la limitazione delle finalità. Ogni trattamento deve basarsi su una base giuridica, come il consenso dell'interessato o obblighi legali, e deve essere comunicato all'interessato tramite un'informativa chiara e completa. \n\nL’informativa è l'atto con cui il Titolare informa l'interessato sugli elementi essenziali del trattamento (chi, cosa, perché, quanto tempo). Deve essere fornita prima o al momento della raccolta, avere un linguaggio chiaro e contenere i contatti del DPO e i diritti dell’interessato. \n\nConsenso e revoca Il GDPR pone il consenso dell'interessato come una delle basi giuridiche fondamentali per il trattamento dei dati personali. Perché sia considerato legittimo deve possedere 4 requisiti: deve essere libero, specifico, informato e inequivocabile. La revoca è un diritto assoluto dell'interessato e deve essere esercitabile con la stessa semplicità con cui il consenso è stato fornito. Nella PA spesso la base giuridica non è il consenso, ma l'esecuzione di un compito di interesse pubblico (come pagare l’IMU o fare la C.I), dove il trattamento è obbligatorio per legge \n\nQuali sono le figure per la protezione dei dati? Le figure si dividono in interne ed esterne: Interne: Titolare (l'Ente), Designati (Dirigenti) e Autorizzati (Dipendenti). Esterne: Responsabili del Trattamento (Fornitori di servizi che trattano i dati per conto del titolare). Di controllo: Il DPO, che fa da \"ponte\" tra l'Ente, i cittadini e l'Autorità Garante."
},
{
    q: "Dati personali, sensibili e giudiziari",
    a: "I dati personali sono tutte le informazioni che identificano una persona, come nome, indirizzo, o codice fiscale. I dati sensibili, oggi detti ‘categorie particolari di dati’, includono quelli che rivelano l’origine razziale, convinzioni religiose, opinioni politiche, salute o orientamento sessuale. I dati giudiziari riguardano condanne penali e reati. Questi ultimi due tipi di dati richiedono maggiori tutele e possono essere trattati solo in casi specifici, nel rispetto del GDPR. \n\nCos’è un data breach? Il Data Breach (Artt. 33-34 GDPR) è una violazione della sicurezza che compromette la riservatezza, l'integrità o la disponibilità dei dati. Il Comune ha l'obbligo di documentare ogni violazione nel proprio \"Registro dei Data Breach\" e, se c'è un rischio per i cittadini, deve notificare il fatto al Garante entro 72 ore. Se il rischio è elevato, deve informare tempestivamente anche gli interessati. Poi mi collego a figure protezione dati >"
},
{
    q: "Il responsabile della protezione dei dati (DPO)",
    a: "Il Responsabile della Protezione dei Dati, o DPO, è una figura chiave prevista dal GDPR per assicurarsi che un'organizzazione gestisca i dati personali nel rispetto delle regole. Tra i suoi compiti principali ci sono: informare e consigliare il titolare del trattamento e i dipendenti sui loro doveri, controllare che il GDPR venga seguito, dare supporto nelle valutazioni d’impatto, e fare da contatto sia per l’autorità di controllo che per le persone interessate. Il DPO lavora in modo indipendente e riferisce direttamente ai vertici dell’organizzazione. \n\nChi è il garante della privacy? Il Garante della Privacy è un'autorità amministrativa indipendente, che vigila sul rispetto della normativa in materia di protezione dei dati personali. Controlla che PA e privati rispettino le norme sulla privacy, riceve i reclami dei cittadini che ritengono violati i propri dati, emette provvedimenti, sanzioni e linee guida. Si coordina con le autorità europee omologhe nell'ambito del GDPR"
}
    ],
    "Anticorruzione": [
       {
    q: "Il PNA",
    a: "Il Piano Nazionale Anticorruzione, o PNA, è uno strumento adottato dall’ANAC che stabilisce le linee guida in materia di prevenzione della corruzione, che ogni ente è tenuto ad adattare al proprio contesto. Ogni amministrazione deve redigere un Piano triennale per la prevenzione della corruzione e della trasparenza, con l’obiettivo di ridurre i rischi di corruzione, rafforzare l’integrità e promuovere la trasparenza nella pubblica amministrazione. Vanno quindi definite strategie, misure e obblighi specifici in relazione ai processi a rischio. Il PNA viene aggiornato periodicamente per tenere conto dei nuovi rischi e delle evoluzioni normative. \n\nCollegamento a PIAO: Da quando è stato introdotto il PIAO, il PTPCT non viene più redatto come documento autonomo ma confluisce come sezione specifica all'interno del PIAO, pur mantenendo il PNA dell'ANAC come riferimento nazionale."
},
{
    q: "ANAC",
    a: "È un organismo indipendente istituito con il compito di prevenire e contrastare la corruzione nella pubblica amministrazione. Ha il ruolo di vigilare sulla trasparenza e la correttezza delle procedure di appalto, affidamento di lavori, servizi e forniture, e di promuovere la cultura dell’integrità e dell’etica pubblica. L’ANAC emana linee guida, monitora gli obblighi di pubblicità e trasparenza, e può intervenire con poteri sanzionatori o proporre misure correttive. È uno strumento chiave per garantire legalità e competizione nel settore pubblico."
}
    ],
    "Fonti normative": [
       {
    q: "TUEL",
    a: "Il TUEL (D.Lgs. 267/2000) raccoglie tutte le norme fondamentali sull'organizzazione e il funzionamento di Comuni, Province e Città metropolitane. Regola l'ordinamento istituzionale, l'organizzazione amministrativa, la finanza locale e la contabilità, rappresentando il punto di equilibrio tra centralismo e decentramento. \n\nTra i principi fondamentali che il TUEL sancisce vi è quello dell'erogazione dei contributi: quando un ente locale eroga contributi o sovvenzioni ai cittadini o alle associazioni, deve farlo nel rispetto dei principi di trasparenza, imparzialità e parità di trattamento, attraverso criteri oggettivi e predeterminati, spesso fissati in appositi regolamenti o bandi pubblici. Nessuno può ricevere un contributo in modo arbitrario. \n\nIl TUEL riconosce inoltre agli enti locali una potestà regolamentare, cioè il potere di adottare propri regolamenti per disciplinare l'organizzazione interna e i servizi erogati, nel rispetto della legge e dello statuto. Accanto a questa, gli enti hanno anche una potestà impositiva: possono istituire e disciplinare tributi locali (come l'IMU o la TARI), entro i limiti fissati dalla legge statale. \n\nInfine il TUEL valorizza la partecipazione dei cittadini alla vita amministrativa, attraverso diverse forme: i referendum consultivi, con cui i cittadini possono esprimere la propria opinione su decisioni importanti; le istanze e petizioni, con cui singoli o gruppi possono sollecitare l'intervento dell'ente; e le consulte o commissioni tematiche, organismi in cui cittadini e associazioni partecipano attivamente alla vita dell'ente."
},
{
    q: "I regolamenti comunali",
    a: "I regolamenti comunali sono atti normativi approvati dal Consiglio Comunale per disciplinare l’organizzazione e il funzionamento dell’ente, ma anche i rapporti con i cittadini. Possono riguardare vari ambiti, come i tributi locali, i servizi pubblici o la partecipazione. Devono rispettare le leggi statali e regionali, ma permettono al Comune di adattare le regole alle proprie esigenze locali. Esempi: Regolamento uffici e servizi. Regolamento di contabilità \n\nRegolamento sull'Ordinamento degli Uffici e dei Servizi (ROUS) Il Regolamento sull'Ordinamento degli Uffici e dei Servizi (ROUS) è uno degli atti più importanti che la Giunta Comunale adotta nell'esercizio della sua autonomia organizzativa. Definisce la struttura interna dell'ente: come sono organizzati gli uffici, come si articolano le responsabilità, quali sono le procedure interne, come vengono gestite le risorse umane. In pratica è il \"regolamento di funzionamento interno\" del Comune."
},
{
    q: "Statuto",
    a: "Lo Statuto è l'atto fondamentale che definisce l'ordinamento interno, l'organizzazione e il funzionamento del Comune. È espressione dell'autonomia statutaria dell'ente e deve rispettare i principi stabiliti dalla legge nazionale, in particolare il TUEL. \n\nCome si approva: è adottato dal Consiglio Comunale con un procedimento rafforzato — richiede il voto favorevole dei 2/3 dei consiglieri in prima votazione, oppure la maggioranza assoluta in due successive votazioni non prima di 30 giorni l'una dall'altra. Dopo l'approvazione viene pubblicato sulla Gazzetta Ufficiale ed entra in vigore dopo 30 giorni. Questo procedimento \"pesante\" riflette l'importanza dello Statuto: non si modifica facilmente. \n\nCosa contiene: disciplina le forme di governo dell'ente, i rapporti tra gli organi (Sindaco, Giunta, Consiglio), le modalità di partecipazione dei cittadini, le forme associative con altri enti, i principi generali sull'organizzazione degli uffici e i criteri per la gestione dei servizi pubblici locali."
},
{
    q: "PIAO",
    a: "Il PIAO (Piano Integrato di Attività e Organizzazione), introdotto dal D.L. 80/2021, nasce con un obiettivo preciso: semplificare. Prima i Comuni dovevano redigere separatamente il Piano della Performance, il Piano Anticorruzione, il Piano dei Fabbisogni del Personale e il Piano della Formazione. Il PIAO li ha accorpati tutti in un unico documento, evitando duplicazioni e frammentazioni. Al suo interno definisce gli obiettivi strategici e operativi dell'ente per i successivi tre anni, le modalità organizzative per raggiungerli, le misure di prevenzione della corruzione e trasparenza, e il fabbisogno di personale con i relativi piani di formazione. Viene approvato dalla Giunta Comunale, su proposta del Segretario Comunale e dei Dirigenti, ha durata triennale e viene aggiornato ogni anno"
},
{
    q: "Le carte dei servizi",
    a: "Introdotte in Italia con la Direttiva del Presidente del Consiglio dei Ministri del 27 gennaio 1994, Le Carte dei Servizi sono documenti con cui la PA (come il Comune di Milano) definisce il rapporto con l'utenza, basandosi sui principi di eguaglianza, imparzialità e continuità. Oltre a informare sulle modalità di erogazione, la loro funzione principale è la fissazione di standard di qualità quantificabili e monitorabili. Rappresentano un vero e proprio 'patto' tra Ente e cittadino: l'amministrazione non solo dichiara cosa fa, ma si assume la responsabilità di farlo entro certi tempi e livelli qualitativi, prevedendo sistemi di reclamo e ristoro in caso di disservizio. In ottica di performance, la Carta dei Servizi permette inoltre all'ente di misurare il grado di soddisfazione dell'utente (customer satisfaction), come previsto dalle linee guida sulla trasparenza e il miglioramento dei servizi pubblici."
}
    ],
    "Pubblico impiego": [
  {
    q: "Pubblico impiego",
    a: "Il Piano Triennale dei Fabbisogni di Personale è il documento con cui l’ente programma per tre anni le assunzioni. Oggi è inserito nel PIAO, viene approvato dalla Giunta e serve obbligatoriamente per poter bandire concorsi. \n\nIl rapporto di lavoro nella Pubblica Amministrazione nasce, di regola, tramite concorso pubblico, previsto dalla Costituzione per garantire imparzialità e buon andamento. Il concorso si svolge attraverso bando, prove, graduatoria e assunzione finale. Esistono però alcune eccezioni, come l’avviamento tramite Centri per l’Impiego, le assunzioni delle categorie protette, la mobilità tra enti e le stabilizzazioni. Tutta la materia è disciplinata dal decreto legislativo 165 del 2001. \n\nDopo il concorso, il rapporto si formalizza con un contratto individuale scritto, che richiama il contratto collettivo nazionale. In esso sono indicati ruolo, sede, retribuzione e periodo di prova. Il periodo di prova è una fase iniziale in cui entrambe le parti possono recedere; se va bene, il dipendente viene confermato. \n\nLa disciplina del lavoro pubblico si basa sulla contrattazione collettiva, che ha due livelli: nazionale, con il CCNL stipulato dall’ARAN, e integrativo, a livello di ente. Il secondo livello serve ad adattare il contratto nazionale, ma non può mai peggiorarlo. L’orario ordinario è di 36 ore settimanali, con limiti giornalieri e periodi di riposo. Sono previsti strumenti di flessibilità come part-time, lavoro agile e straordinari. \n\nIl rapporto può cessare per cause volontarie, come dimissioni o pensionamento, oppure involontarie, come licenziamento disciplinare o mancato superamento della prova. Le sanzioni disciplinari sono graduate in base alla gravità e vanno dal rimprovero fino al licenziamento. Il procedimento deve sempre garantire la difesa del dipendente e rispettare tempi precisi. Il principio fondamentale è la proporzionalità: la sanzione deve essere adeguata al fatto e non si può essere puniti due volte per lo stesso comportamento."
},
{
    q: "I doveri del dipendente pubblico",
    a: "Il dipendente pubblico ha il dovere di servire lo Stato e i cittadini con correttezza, imparzialità e trasparenza. Deve rispettare le leggi, il codice di comportamento e i regolamenti interni. È tenuto a garantire efficienza, riservatezza, collaborazione e rispetto della gerarchia. Ogni azione deve essere seguire il principio di correttezza e essere orientata all’interesse pubblico, evitando conflitti di interesse e comportamenti che possano danneggiare l’immagine dell’amministrazione. \n\nTra i doveri più rilevanti vi è quello di esclusività, previsto dall'art. 53 del D.Lgs. 165/2001: il dipendente pubblico deve lavorare solo per la PA. Esistono attività vietate, come il commercio o un impiego privato; attività autorizzabili, come incarichi occasionali per cui è necessaria la previa autorizzazione dell'ente — che deve rispondere entro 30 giorni, altrimenti scatta il silenzio-diniego; e attività libere, come la scrittura o il volontariato. Il vincolo di esclusività decade per i part-time inferiori al 50%. La violazione può portare al licenziamento e all'obbligo di restituire i compensi percepiti indebitamente."
},
{
    q: "I diritti del dipendente pubblico",
    a: "Il dipendente pubblico ha diritto a un trattamento economico e normativo definito dai CCNL. I diritti si dividono in patrimoniali — come lo stipendio, le indennità e il TFR — e non patrimoniali — come le ferie, i permessi, i diritti sindacali e la tutela della dignità professionale. \n\nSul piano economico, la retribuzione si divide in una parte fissa (trattamento fondamentale), composta dallo stipendio tabellare, dall'indennità di comparto, dalla tredicesima e dal differenziale stipendiale; e una parte accessoria (variabile), legata alla performance e alle condizioni di lavoro, che comprende premi di produttività, indennità di posizione e risultato e lo straordinario. La parte accessoria è finanziata tramite il Fondo per la contrattazione integrativa, soggetto a limiti di legge rigidi che il Comune non può superare. \n\nSul piano delle assenze, il dipendente ha diritto a ferie (28-32 giorni annui), permessi retribuiti per motivi personali, lutto, Legge 104 e congedo matrimoniale. La malattia ha una disciplina particolare: nei primi 10 giorni di ogni evento viene applicata la cosiddetta trattenuta Brunetta (vengono tagliate le indennità accessorie), e il dipendente ha diritto alla conservazione del posto per un massimo di 18 mesi in un triennio (periodo di comporto), con retribuzione decrescente nel tempo. I congedi di maternità (5 mesi al 100%) e parentali (facoltativi, con retribuzione variabile) tutelano la genitorialità. Infine le aspettative sono assenze non retribuite, concesse per motivi personali o professionali, per un massimo di 12 mesi in un triennio. \n\nSul piano della flessibilità, la PA può ricorrere alla flessibilità temporale (orari flessibili, banca delle ore) e alla flessibilità spaziale, tra cui il lavoro agile (L. 81/2017), basato sul raggiungimento di obiettivi anziché sul controllo dell'orario. E’ inoltre possibile il lavoro da remoto, previa autorizzazione e comunicazione di una sede stabile. Richiede un accordo individuale, garantisce il diritto alla disconnessione e non può penalizzare la carriera o la retribuzione del dipendente. Oggi il lavoro agile deve essere programmato all'interno del PIAO."
},
{
    q: "Codice di comportamento",
    a: "Il Codice di comportamento dell’amministrazione è un insieme di regole etiche e di condotta che ogni dipendente pubblico deve rispettare. Serve a garantire integrità, trasparenza, imparzialità e buon andamento dell’azione amministrativa. \n\nÈ previsto dal D.Lgs. 165/2001 ed è integrato dai singoli codici adottati dalle amministrazioni. Sul piano dei contenuti, disciplina i rapporti con i cittadini — che devono essere improntati a cortesia, disponibilità e rispetto — l'uso corretto delle risorse pubbliche, il dovere di astensione in caso di conflitto di interessi e il divieto di utilizzare la propria posizione per ottenere vantaggi personali. \n\nIl dipendente non può accettare regali, compensi o altre utilità da soggetti che abbiano o possano avere rapporti con la PA, salvo quelli di modico valore, fissato convenzionalmente in non più di 150 euro. Anche in quel caso, se il regalo può anche solo apparire come una forma di influenza, il dipendente deve rifiutarlo. I regali ricevuti in violazione di questa regola devono essere restituiti o consegnati all'amministrazione. \n\nLa violazione del codice di comportamento costituisce illecito disciplinare e può portare a sanzioni fino al licenziamento nei casi più gravi."
}
    ]
,
    "Sicurezza": [
{
    q: "Datore di lavoro",
    a: "Nel contesto del D.Lgs. 81/2008 (Testo Unico sulla Sicurezza sul Lavoro), il datore di lavoro è il soggetto che ha la responsabilità principale in materia di salute e sicurezza. Nel caso di un ente pubblico come il Comune, il datore di lavoro ai fini della sicurezza coincide con il dirigente a cui sono attribuiti poteri di gestione e spesa, non necessariamente con il Sindaco. \n\nI suoi obblighi principali sono non delegabili: deve redigere il DVR (Documento di Valutazione dei Rischi) e nominare il RSPP (Responsabile del Servizio di Prevenzione e Protezione). Tutto il resto — formazione, sorveglianza sanitaria, fornitura dei DPI — può essere delegato ad altri soggetti, ma la responsabilità ultima rimane sempre in capo a lui."
},
{
    q: "RSPP (Responsabile del Servizio Prevenzione e Protezione)",
    a: "L’RSPP è una figura obbligatoria in ogni ente o azienda, prevista dal Testo Unico sulla sicurezza sul lavoro. Ha il compito di individuare i rischi presenti nei luoghi di lavoro e proporre misure per eliminarli o ridurli. Collabora con il datore di lavoro nella redazione del DVR, cioè il Documento di Valutazione dei Rischi. Non ha potere decisionale, ma un ruolo tecnico fondamentale per tutelare la salute e la sicurezza dei lavoratori. \n\nL'RLS (Rappresentante dei Lavoratori per la Sicurezza) è la figura che rappresenta i lavoratori in materia di salute e sicurezza. A differenza dell'RSPP, non viene nominato dal datore di lavoro ma eletto direttamente dai lavoratori. Ha il diritto di essere consultato sulla valutazione dei rischi, di accedere ai luoghi di lavoro e di ricevere informazioni e formazione specifica. È il punto di raccordo tra i lavoratori e il datore di lavoro su tutte le questioni legate alla sicurezza. \n\nIl medico competente è invece un professionista medico nominato dal datore di lavoro, obbligatorio quando la legge prevede la sorveglianza sanitaria — cioè quando i lavoratori sono esposti a rischi specifici come agenti chimici, rumore, videoterminali. Il suo compito principale è effettuare le visite mediche periodiche e rilasciare il giudizio di idoneità alla mansione: può dichiarare il lavoratore idoneo, idoneo con limitazioni o non idoneo."
},
{
    q: "DVR",
    a: "Il DVR (Documento di Valutazione dei Rischi) è il documento fondamentale del sistema di sicurezza aziendale, obbligatorio per tutti i datori di lavoro. È redatto dal datore di lavoro insieme all'RSPP e al medico competente, sentito l'RLS. Contiene l'analisi di tutti i rischi presenti nell'ambiente di lavoro, le misure preventive e protettive adottate per ridurli, i dispositivi di protezione individuale necessari e il programma delle misure da attuare nel tempo per migliorare la sicurezza. Non è un documento statico — deve essere aggiornato ogni volta che cambiano le condizioni di lavoro, l'organizzazione, i processi produttivi o in seguito a infortuni significativi."
},
{
    q: "Informazione e formazione",
    a: "Il D.Lgs. 81/2008 pone grande enfasi sulla formazione e informazione dei lavoratori, considerandole strumenti fondamentali di prevenzione. L'informazione consiste nel trasmettere al lavoratore le conoscenze sui rischi presenti nel suo ambiente di lavoro, sulle misure di prevenzione adottate e sui comportamenti da tenere in caso di emergenza. È un flusso essenzialmente unidirezionale: il datore informa il lavoratore. La formazione è invece un processo più strutturato e interattivo, che mira a sviluppare competenze concrete sulla sicurezza. Deve essere specifica per la mansione svolta, effettuata da soggetti qualificati e ripetuta periodicamente o ogni volta che cambiano le condizioni di lavoro. Entrambe devono avvenire durante l'orario di lavoro e a spese del datore di lavoro — non possono essere un onere per il lavoratore."
},
{
    q: "Doveri dipendente e Preposto",
    a: "La sicurezza sul lavoro non è una responsabilità esclusiva del datore di lavoro — anche il lavoratore ha obblighi precisi previsti dal D.Lgs. 81/2008. Deve prendersi cura della propria salute e di quella dei colleghi, utilizzare correttamente i DPI (Dispositivi di Protezione Individuale) forniti, seguire le istruzioni ricevute e segnalare immediatamente al datore o al preposto qualsiasi situazione di pericolo. Non può quindi considerarsi un soggetto passivo — è parte attiva del sistema di sicurezza. Il preposto è la figura intermedia tra il datore di lavoro e i lavoratori — tipicamente un capo squadra, un capo ufficio o un responsabile di reparto. Ha il compito di sovrintendere e vigilare sul corretto comportamento dei lavoratori durante l'attività lavorativa. Se rileva comportamenti non conformi alle norme di sicurezza deve intervenire immediatamente, e se necessario interrompere l'attività e informare il datore di lavoro."
}
    ],
    "Appalti": [
{
    q: "I principi dell’evidenza pubblica",
    a: "I principi dell’evidenza pubblica guidano l’attività della Pubblica Amministrazione nei contratti e negli appalti. L’obbiettivo è quello di garantire evidenza pubblica, ovvero assicurare che le procedure siano trasparenti, imparziali e aperte alla concorrenza. Sono codificati nei primi tre articoli del Codice dei contratti pubblici: principio del risultato, della fiducia, dell’accesso al mercato. L’obiettivo è selezionare il miglior offerente nel rispetto dell’interesse pubblico e della legalità."
},
{
    q: "I requisiti di partecipazione",
    a: "I requisiti di partecipazione sono le condizioni che le imprese devono possedere per poter partecipare a una gara pubblica. Si dividono in requisiti generali, come l'assenza di condanne penali o irregolarità fiscali; requisiti di idoneità professionale, come l'iscrizione alla Camera di Commercio; e requisiti economico-finanziari e tecnico-professionali, che garantiscono la capacità di eseguire il contratto. Tra i requisiti generali rientra anche il DURC (Documento Unico di Regolarità Contributiva), una certificazione che attesta che l'impresa è in regola con i pagamenti verso INPS, INAIL e casse edili — chi non è in regola viene escluso dalla gara. \n\nChi non possiede questi requisiti incorre nelle cause di esclusione, che possono essere obbligatorie — come una condanna penale definitiva per reati gravi — oppure facoltative, rimesse alla valutazione della stazione appaltante. Tuttavia non ogni irregolarità porta automaticamente all'esclusione. Il soccorso istruttorio è lo strumento che permette alla stazione appaltante di invitare il concorrente a regolarizzare o integrare la documentazione mancante o irregolare, entro un termine perentorio. Non può però essere usato per modificare l'offerta economica o tecnica — serve solo a sanare vizi formali, non sostanziali."
},
{
    q: "I criteri di aggiudicazione",
    a: "Nei contratti pubblici, i criteri di aggiudicazione servono a individuare l’offerta migliore. I due principali sono: il prezzo più basso, usato per forniture standard o ripetitive, e l’offerta economicamente più vantaggiosa, che valuta anche qualità, tempi e aspetti tecnici. Quest’ultima è molto usata quando conta non solo il costo, ma anche il valore complessivo della proposta. La scelta del criterio dipende dal tipo di appalto e dall’interesse pubblico da tutelare."
},
{
    q: "I criteri di aggiudicazione",
    a: "Nei contratti pubblici, i criteri di aggiudicazione servono a individuare l’offerta migliore. I due principali sono: il prezzo più basso, usato per forniture standard o ripetitive, e l’offerta economicamente più vantaggiosa, che valuta anche qualità, tempi e aspetti tecnici. Quest’ultima è molto usata quando conta non solo il costo, ma anche il valore complessivo della proposta. La scelta del criterio dipende dal tipo di appalto e dall’interesse pubblico da tutelare."
},
{
    q: "L’affidamento diretto",
    a: "L’affidamento diretto è una modalità semplificata di assegnazione degli appalti pubblici, che non richiede una vera e propria gara. La stazione appaltante può scegliere direttamente l’operatore economico, motivando la scelta e rispettando i limiti di importo stabiliti dal Codice dei contratti. Attualmente, è possibile ricorrere all’affidamento diretto per lavori fino a 150.000 euro e per servizi e forniture fino a 140.000 euro. Questa procedura è utilizzata soprattutto per lavori, servizi e forniture di modesta entità, poiché consente rapidità ed efficienza, sempre nel rispetto dei principi di trasparenza e buon andamento."
},
{
    q: "Le procedure aperte e ristrette",
    a: "Le procedure aperte e ristrette sono due forme di gara previste dal Codice dei contratti pubblici. Nella procedura aperta, chiunque può partecipare presentando direttamente un'offerta. È la più trasparente e utilizzata. Nella procedura ristretta, invece, solo gli operatori invitati dalla stazione appaltante, dopo una selezione preliminare, possono presentare offerta. Entrambe garantiscono concorrenza, ma la ristretta è utile quando serve una prima verifica dei requisiti. \n\nUna volta individuato il vincitore e comunicata l'aggiudicazione, non si passa immediatamente alla firma del contratto. La legge impone un periodo di sospensione obbligatoria chiamato stand still, della durata di 35 giorni dalla comunicazione dell'aggiudicazione. Questo periodo serve a tutelare i concorrenti non aggiudicatari, che possono utilizzare questo tempo per verificare la regolarità della procedura e presentare eventualmente ricorso al TAR. Solo dopo la scadenza dello stand still, e in assenza di ricorsi, il contratto può essere firmato."
},
{
    q: "Il ruolo del RUP",
    a: "Il RUP è la figura centrale in ogni procedura di appalto. È nominato dalla stazione appaltante e ha il compito di seguire tutte le fasi: dalla programmazione alla progettazione, fino all’esecuzione del contratto. Coordina i vari soggetti coinvolti, controlla tempi, costi e qualità e garantisce il rispetto delle norme. Il suo ruolo è previsto dal Codice dei contratti pubblici e assicura trasparenza, efficienza e regolarità nell’intero processo."
},
{
    q: "L’esecuzione del contratto pubblico",
    a: "L’esecuzione del contratto pubblico è la fase in cui l’appaltatore realizza concretamente quanto previsto dal contratto, che sia un lavoro, un servizio o una fornitura. In questa fase è fondamentale il controllo da parte della stazione appaltante, che verifica il rispetto di tempi, costi e qualità. Il RUP supervisiona l’esecuzione e può adottare misure in caso di ritardi o inadempienze. L’obiettivo è garantire il buon esito dell’appalto e tutelare l’interesse pubblico."
}
    ],
    "Contabilità": [
{
    q: "Fonti di finanziamento e Entrate tributarie del comune",
    a: "Il Comune finanzia la propria attività attraverso diverse fonti di entrata, che si dividono in tre grandi categorie. \n\nLe entrate tributarie, derivanti dalla potestà impositiva dell'ente: l'IMU (imposta sul patrimonio immobiliare), la TARI (tassa sui rifiuti, corrispettivo di un servizio specifico) e l'Addizionale Comunale IRPEF. Vale la pena ricordare la distinzione tra imposta — dovuta indipendentemente da un servizio — e tassa — legata a un servizio concreto reso dalla PA. \n\nLe entrate extratributarie, che comprendono i proventi dei servizi pubblici (es. tariffe per asili nido, parcheggi, mense scolastiche), i canoni per l'uso di beni comunali e le sanzioni amministrative. \n\nI trasferimenti, cioè le risorse che arrivano dall'esterno: dallo Stato (come il Fondo di Solidarietà Comunale), dalla Regione e dall'Unione Europea sotto forma di contributi e finanziamenti."
},
{
    q: "IL DUP",
    a: "Il DUP (Documento Unico di Programmazione) è il principale strumento di pianificazione del Comune. Serve a definire le linee strategiche e operative dell'ente e viene approvato dal Consiglio Comunale, rappresentando la base su cui costruire il bilancio di previsione. Si articola in due sezioni: la Sezione Strategica (SeS), con orizzonte di almeno 5 anni, che definisce le linee di mandato e gli obiettivi di lungo periodo; e la Sezione Operativa (SeO), con orizzonte triennale, che traduce quegli obiettivi in programmi concreti collegandoli alle risorse disponibili."
},
{
    q: "Il Bilancio di Previsione",
    a: "Il bilancio di previsione è il principale strumento di programmazione finanziaria del Comune. Viene approvato ogni anno dal Consiglio Comunale e indica, in modo preventivo, tutte le entrate e le spese dell'ente per il triennio successivo. È un documento tecnico ma anche politico, perché riflette le scelte strategiche dell'amministrazione. \n\nSi basa su alcuni principi fondamentali: annualità, universalità, veridicità e pareggio. Il pareggio di bilancio è il principio contabile fondamentale che impone all’ente pubblico di non prevedere spese superiori alle entrate, garantendo l’equilibrio economico-finanziario. Il rispetto del pareggio è essenziale per garantire la sostenibilità finanziaria dell’ente e il buon uso delle risorse pubbliche, evitando deficit e indebitamento eccessivo. \n\nSul piano della struttura, le entrate si classificano per titolo (tributarie, extratributarie, trasferimenti, entrate in conto capitale...) e le spese si dividono in spese correnti — per il funzionamento ordinario dell'ente come stipendi e utenze — e spese in conto capitale (entrate \"una tantum\" o legate a grandi opere, per costruire, acquistare beni durevoli (immobili, macchinari) o estinguere debiti.) . Queste ultime si collegano spesso al Fondo Pluriennale Vincolato, quando l'investimento si sviluppa su più anni. \n\nSul piano dell'iter, la Giunta predispone lo schema di bilancio e lo sottopone al Consiglio, che deve approvarlo entro il 31 dicembre dell'anno precedente. Se il bilancio non viene approvato nei termini si entra in esercizio provvisorio, che permette di spendere mensilmente non più di un dodicesimo delle spese previste, solo per le spese strettamente necessarie. Se invece il bilancio non è nemmeno stato predisposto dalla Giunta si parla di gestione provvisoria, situazione ancora più limitata. \n\nInfine il bilancio non è immutabile: può essere modificato nel corso dell'anno tramite variazioni di bilancio. Quelle ordinarie sono approvate dal Consiglio. In caso di urgenza, la Giunta può adottare variazioni in via d'urgenza, ma il Consiglio deve ratificarle entro 60 giorni, e comunque entro il 31 dicembre dell'anno in corso. \n\nI debiti fuori bilancio sono somme che il Comune deve pagare, ma che non erano previste nel bilancio. Nascono, ad esempio, da sentenze dei tribunali, accordi o situazioni impreviste. Per poterli riconoscere e pagare, serve una delibera del Consiglio comunale, che spiega chiaramente il motivo del debito. Questa procedura serve a garantire trasparenza e correttezza nei conti pubblici."
},
{
    q: "Il pareggio di bilancio",
    a: "Il pareggio di bilancio è il principio contabile fondamentale che impone all’ente pubblico di non prevedere spese superiori alle entrate, garantendo l’equilibrio economico-finanziario. Il rispetto del pareggio è essenziale per garantire la sostenibilità finanziaria dell’ente e il buon uso delle risorse pubbliche, evitando deficit e indebitamento eccessivo."
},
{
    q: "I debiti fuori bilancio",
    a: "I debiti fuori bilancio sono somme che il Comune deve pagare, ma che non erano previste nel bilancio. Nascono, ad esempio, da sentenze dei tribunali, accordi o situazioni impreviste. Per poterli riconoscere e pagare, serve una delibera del Consiglio comunale, che spiega chiaramente il motivo del debito. Questa procedura serve a garantire trasparenza e correttezza nei conti pubblici."
},
{
    q: "PEG",
    a: "Il PEG (Piano Esecutivo di Gestione) è lo strumento con cui la Giunta traduce gli obiettivi del bilancio e del DUP in attività concrete da realizzare. Assegna le risorse ai dirigenti e specifica cosa devono fare e con quali mezzi, collegando la programmazione politica alla gestione amministrativa. \n\nSul piano dei contenuti, il PEG definisce per ciascun dirigente: gli obiettivi da raggiungere, le risorse finanziarie assegnate (i capitoli di bilancio di cui può disporre), le risorse umane e strumentali a disposizione e gli indicatori di risultato con cui verrà valutata la performance. È quindi anche la base su cui si fonda la valutazione dei dirigenti e, di riflesso, la distribuzione del salario accessorio. \n\nSul piano dei tempi, viene approvato dalla Giunta dopo l'approvazione del bilancio di previsione, di norma entro 20 giorni. Ha durata annuale, coerente con il bilancio di riferimento."
},
{
    q: "Le fasi dell’entrata",
    a: "Le entrate degli enti locali si articolano in tre fasi fondamentali. La prima è l’accertamento, in cui l’ente verifica l’esistenza di un credito certo, liquido ed esigibile, determinando l’importo da incassare, il debitore e la scadenza. La seconda è la riscossione, che rappresenta il momento in cui il debitore effettua il pagamento, ad esempio tramite bonifico o altri mezzi previsti. Infine, c’è il versamento, ovvero il trasferimento effettivo delle somme incassate nelle casse dell’ente, completando così il processo di acquisizione dell’entrata."
},
{
    q: "Le fasi dell’uscita",
    a: "Le uscite del Comune seguono un processo ordinato diviso in quattro fasi. \n\nLa prima è l'impegno: la PA prenota una somma sul bilancio per far fronte a una spesa specifica, verificando che ci sia la copertura finanziaria. Prima che l'impegno sia formalizzato, il responsabile del servizio finanziario deve apporre il visto di regolarità contabile, che attesta l'esistenza della copertura finanziaria e la regolarità contabile dell'atto. Senza questo visto la spesa non può essere impegnata. \n\nLa seconda è la liquidazione: una volta che la prestazione è stata eseguita, il responsabile del servizio che ha dato esecuzione al provvedimento di spesa verifica che quanto ricevuto corrisponda a quanto pattuito — in termini di qualità, quantità e tempi — e determina l'esatto importo da pagare. È una competenza propria del dirigente, non delegabile al servizio finanziario. \n\nLa terza è l'ordinazione: il dirigente emette il mandato di pagamento, cioè l'atto formale con cui dispone al tesoriere di effettuare il pagamento. \n\nLa quarta è il pagamento vero e proprio, eseguito dal tesoriere — di norma una banca convenzionata con il Comune — che estingue l'obbligazione. \n\nOgni fase ha il suo responsabile e il suo controllo. Questo sistema a più livelli garantisce che i soldi pubblici vengano spesi in modo controllato, tracciabile e regolare. 👍"
},
{
    q: "Residui attivi",
    a: "I residui attivi sono entrate accertate dal Comune in un anno, ma non ancora incassate entro la fine dell’esercizio. In pratica, rappresentano crediti che l’ente deve ancora riscuotere. Possono riguardare tasse, trasferimenti o altri introiti. Vengono riportati nel bilancio dell’anno successivo e tenuti sotto controllo per garantire che non si accumulino troppi crediti non riscossi."
},
{
    q: "Residui passivi",
    a: "I residui passivi sono spese che il Comune ha impegnato, cioè autorizzato, in un anno, ma che non sono ancora state pagate entro la fine dell’esercizio. Sono quindi debiti che l’ente deve ancora saldare. Possono riguardare lavori, servizi o forniture già ricevuti. Vengono riportati nel bilancio dell’anno successivo per garantire che tutte le uscite siano correttamente gestite e monitorate."
},
{
    q: "Il rendiconto di gestione",
    a: "Il rendiconto di gestione è il documento con cui, alla fine dell’anno, il Comune dimostra come ha usato le risorse pubbliche. Serve a confrontare ciò che era stato previsto nel bilancio con quello che è stato effettivamente realizzato. È composto da tre parti: conto del bilancio, conto economico e conto del patrimonio. Viene approvato dal Consiglio e garantisce trasparenza e responsabilità nella gestione finanziaria."
},
{
    q: "Fondo Pluriennale Vincolato (FPV)",
    a: "È uno strumento contabile che aiuta a gestire i progetti che durano più anni. Permette di 'mettere da parte' quelle risorse, quei soldi che sono già destinati, o 'vincolati', per una spesa futura. Questo assicura che il bilancio sia sempre preciso, mostrando esattamente quali impegni reali l'ente ha preso, anche se la spesa avverrà più avanti. È fondamentale per la trasparenza e la corretta gestione dei fondi"
}
    ]

};
